name: "Nacos 配置修改"
version: "v0.0.1"
description: "update nacos config"
image: koderover.tencentcloudcr.com/koderover-public/update-nacos-config:v0.0.1-amd64

envs:
- name: CONTENT
  value: $(inputs.CONTENT)
- name: SERVER_IP
  value: $(inputs.SERVER_IP)
- name: SERVER_PORT
  value: $(inputs.SERVER_PORT)
- name: TENANT_ID
  value: $(inputs.TENANT_ID)
- name: DATA_ID
  value: $(inputs.DATA_ID)
- name: GROUP
  value: $(inputs.GROUP)
- name: TYPE
  value: $(inputs.TYPE)
- name: USER_NAME
  value: $(inputs.USER_NAME)
- name: PASSWORD
  value: $(inputs.PASSWORD)
- name: SCHEMA
  value: $(inputs.SCHEMA)
  
inputs:
- name: CONTENT
  description: "config file content"
  type: text
  default: ""
- name: SERVER_IP
  description: "nacos server ip"
  type: string
  default: ""
- name: SERVER_PORT
  description: "nacos server port"
  type: string
  default: "0"
- name: TENANT_ID
  description: "nacos namespace id"
  type: string
  default: ""
- name: DATA_ID
  description: "nacos config data id"
  type: string
  default: ""
- name: GROUP
  description: "nacos config group"
  type: string
  default: ""
- name: TYPE
  description: "nacos config type: properties/xml/json/text/html/yaml"
  type: string
  default: ""
- name: USER_NAME
  description: "nacos user name"
  type: string
  default: ""
- name: PASSWORD
  description: "nacos password"
  type: string
  default: ""
- name: SCHEMA
  description: "nacos server schema"
  type: string
  default: "http"